
package web;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapAccount", targetNamespace = "http://web/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapAccount {


    /**
     * 
     * @param date
     * @param string
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "findByDateUserName", partName = "findByDateUserName")
    @Action(input = "http://web/SoapAccount/findByDateUserNameRequest", output = "http://web/SoapAccount/findByDateUserNameResponse")
    public String findByDateUserName(
        @WebParam(name = "String", partName = "String")
        String string,
        @WebParam(name = "Date", partName = "Date")
        String date);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "FindAll")
    @WebResult(name = "findAll", partName = "findAll")
    @Action(input = "http://web/SoapAccount/FindAllRequest", output = "http://web/SoapAccount/FindAllResponse")
    public String findAll();

    /**
     * 
     * @param string
     * @return
     *     returns web.GroupAccount
     */
    @WebMethod
    @WebResult(name = "findByUserName", partName = "findByUserName")
    @Action(input = "http://web/SoapAccount/findUserRequest", output = "http://web/SoapAccount/findUserResponse")
    public GroupAccount findUser(
        @WebParam(name = "String", partName = "String")
        String string);

}
