
package web;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapEmployee", targetNamespace = "http://web/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapEmployee {


    /**
     * 
     * @return
     *     returns web.GroupEmployee
     */
    @WebMethod
    @WebResult(name = "displayEmployee", partName = "displayEmployee")
    @Action(input = "http://web/SoapEmployee/callDisplayEmployeeRequest", output = "http://web/SoapEmployee/callDisplayEmployeeResponse")
    public GroupEmployee callDisplayEmployee();

    /**
     * 
     * @param employee
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "writeEmployee", partName = "writeEmployee")
    @Action(input = "http://web/SoapEmployee/callWriteEmployeeRequest", output = "http://web/SoapEmployee/callWriteEmployeeResponse")
    public boolean callWriteEmployee(
        @WebParam(name = "Employee", partName = "Employee")
        Employee employee);

    /**
     * 
     * @param integer
     * @return
     *     returns web.GroupEmployee
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://web/SoapEmployee/callFilterPinCodesRequest", output = "http://web/SoapEmployee/callFilterPinCodesResponse")
    public GroupEmployee callFilterPinCodes(
        @WebParam(name = "Integer", partName = "Integer")
        int integer);

}
