
package web;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AccountSoapService", targetNamespace = "http://web/", wsdlLocation = "http://localhost:3000/findUserName?wsdl")
public class AccountSoapService
    extends Service
{

    private final static URL ACCOUNTSOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACCOUNTSOAPSERVICE_EXCEPTION;
    private final static QName ACCOUNTSOAPSERVICE_QNAME = new QName("http://web/", "AccountSoapService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:3000/findUserName?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACCOUNTSOAPSERVICE_WSDL_LOCATION = url;
        ACCOUNTSOAPSERVICE_EXCEPTION = e;
    }

    public AccountSoapService() {
        super(__getWsdlLocation(), ACCOUNTSOAPSERVICE_QNAME);
    }

    public AccountSoapService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACCOUNTSOAPSERVICE_QNAME, features);
    }

    public AccountSoapService(URL wsdlLocation) {
        super(wsdlLocation, ACCOUNTSOAPSERVICE_QNAME);
    }

    public AccountSoapService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACCOUNTSOAPSERVICE_QNAME, features);
    }

    public AccountSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AccountSoap
     */
    @WebEndpoint(name = "AccountSoapPort")
    public AccountSoap getAccountSoapPort() {
        return super.getPort(new QName("http://web/", "AccountSoapPort"), AccountSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccountSoap
     */
    @WebEndpoint(name = "AccountSoapPort")
    public AccountSoap getAccountSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://web/", "AccountSoapPort"), AccountSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACCOUNTSOAPSERVICE_EXCEPTION!= null) {
            throw ACCOUNTSOAPSERVICE_EXCEPTION;
        }
        return ACCOUNTSOAPSERVICE_WSDL_LOCATION;
    }

}
