
package soap.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Transaction", targetNamespace = "http://services.soap/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Transaction {


    /**
     * 
     * @param transactionListJson
     */
    @WebMethod
    @Action(input = "http://services.soap/Transaction/receiveTransactionsRequest", output = "http://services.soap/Transaction/receiveTransactionsResponse")
    public void receiveTransactions(
        @WebParam(name = "transactionListJson", mode = WebParam.Mode.INOUT, partName = "transactionListJson")
        Holder<String> transactionListJson);

}
