
package soap.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TransactionService", targetNamespace = "http://services.soap/", wsdlLocation = "http://localhost:8083/soap/transactions?wsdl")
public class TransactionService
    extends Service
{

    private final static URL TRANSACTIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRANSACTIONSERVICE_EXCEPTION;
    private final static QName TRANSACTIONSERVICE_QNAME = new QName("http://services.soap/", "TransactionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8083/soap/transactions?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRANSACTIONSERVICE_WSDL_LOCATION = url;
        TRANSACTIONSERVICE_EXCEPTION = e;
    }

    public TransactionService() {
        super(__getWsdlLocation(), TRANSACTIONSERVICE_QNAME);
    }

    public TransactionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRANSACTIONSERVICE_QNAME, features);
    }

    public TransactionService(URL wsdlLocation) {
        super(wsdlLocation, TRANSACTIONSERVICE_QNAME);
    }

    public TransactionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRANSACTIONSERVICE_QNAME, features);
    }

    public TransactionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransactionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Transaction
     */
    @WebEndpoint(name = "TransactionPort")
    public Transaction getTransactionPort() {
        return super.getPort(new QName("http://services.soap/", "TransactionPort"), Transaction.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Transaction
     */
    @WebEndpoint(name = "TransactionPort")
    public Transaction getTransactionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.soap/", "TransactionPort"), Transaction.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRANSACTIONSERVICE_EXCEPTION!= null) {
            throw TRANSACTIONSERVICE_EXCEPTION;
        }
        return TRANSACTIONSERVICE_WSDL_LOCATION;
    }

}
