
package web;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapEmployeeService", targetNamespace = "http://web/", wsdlLocation = "http://localhost:5001/prash?wsdl")
public class SoapEmployeeService
    extends Service
{

    private final static URL SOAPEMPLOYEESERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPEMPLOYEESERVICE_EXCEPTION;
    private final static QName SOAPEMPLOYEESERVICE_QNAME = new QName("http://web/", "SoapEmployeeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5001/prash?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPEMPLOYEESERVICE_WSDL_LOCATION = url;
        SOAPEMPLOYEESERVICE_EXCEPTION = e;
    }

    public SoapEmployeeService() {
        super(__getWsdlLocation(), SOAPEMPLOYEESERVICE_QNAME);
    }

    public SoapEmployeeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPEMPLOYEESERVICE_QNAME, features);
    }

    public SoapEmployeeService(URL wsdlLocation) {
        super(wsdlLocation, SOAPEMPLOYEESERVICE_QNAME);
    }

    public SoapEmployeeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPEMPLOYEESERVICE_QNAME, features);
    }

    public SoapEmployeeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapEmployeeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapEmployee
     */
    @WebEndpoint(name = "SoapEmployeePort")
    public SoapEmployee getSoapEmployeePort() {
        return super.getPort(new QName("http://web/", "SoapEmployeePort"), SoapEmployee.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapEmployee
     */
    @WebEndpoint(name = "SoapEmployeePort")
    public SoapEmployee getSoapEmployeePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://web/", "SoapEmployeePort"), SoapEmployee.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPEMPLOYEESERVICE_EXCEPTION!= null) {
            throw SOAPEMPLOYEESERVICE_EXCEPTION;
        }
        return SOAPEMPLOYEESERVICE_WSDL_LOCATION;
    }

}
