//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.23 at 11:33:18 AM IST 
//


package links.transactions;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the links.transactions package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: links.transactions
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateRemarksTransactionRequest }
     */
    public UpdateRemarksTransactionRequest createUpdateRemarksTransactionRequest() {
        return new UpdateRemarksTransactionRequest();
    }

    /**
     * Create an instance of {@link Transactions }
     */
    public Transactions createTransactions() {
        return new Transactions();
    }

    /**
     * Create an instance of {@link RemoveByDateRequest }
     */
    public RemoveByDateRequest createRemoveByDateRequest() {
        return new RemoveByDateRequest();
    }

    /**
     * Create an instance of {@link FilterByReceiverResponse }
     */
    public FilterByReceiverResponse createFilterByReceiverResponse() {
        return new FilterByReceiverResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link NewTransactionRequest }
     */
    public NewTransactionRequest createNewTransactionRequest() {
        return new NewTransactionRequest();
    }

    /**
     * Create an instance of {@link FilterByAmountResponse }
     */
    public FilterByAmountResponse createFilterByAmountResponse() {
        return new FilterByAmountResponse();
    }

    /**
     * Create an instance of {@link FilterByReceiverRequest }
     */
    public FilterByReceiverRequest createFilterByReceiverRequest() {
        return new FilterByReceiverRequest();
    }

    /**
     * Create an instance of {@link NewTransactionResponse }
     */
    public NewTransactionResponse createNewTransactionResponse() {
        return new NewTransactionResponse();
    }

    /**
     * Create an instance of {@link FilterBySenderResponse }
     */
    public FilterBySenderResponse createFilterBySenderResponse() {
        return new FilterBySenderResponse();
    }

    /**
     * Create an instance of {@link FilterBySenderRequest }
     */
    public FilterBySenderRequest createFilterBySenderRequest() {
        return new FilterBySenderRequest();
    }

    /**
     * Create an instance of {@link RemoveByDateResponse }
     */
    public RemoveByDateResponse createRemoveByDateResponse() {
        return new RemoveByDateResponse();
    }

    /**
     * Create an instance of {@link UpdateRemarksTransactionResponse }
     */
    public UpdateRemarksTransactionResponse createUpdateRemarksTransactionResponse() {
        return new UpdateRemarksTransactionResponse();
    }

    /**
     * Create an instance of {@link FilterByAmountRequest }
     */
    public FilterByAmountRequest createFilterByAmountRequest() {
        return new FilterByAmountRequest();
    }

}
